version: 2
updates:
  - package-ecosystem: pip
    directory: "/semantic-search/indexer"
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: "/semantic-search/query-api"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
