apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: risk-service-pdb
  namespace: tenant-trading
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: risk-service
