apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: platform-critical
value: 100000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: Platform critical workloads.
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-observability
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
